# Dataset di partenza
(https://www.harmo.org/jsirwin/RoundHillDiscussion.html)

In [1]:
from util import load_from_excel

fname1 = 'RHILL1Update01.xls'
fname2 = 'RHILL2Update01.xls'

data1 = load_from_excel(fname1, sheet_name=2)
data2 = load_from_excel(fname2, sheet_name=2)

meteo1 = load_from_excel(fname1, sheet_name=1)
meteo2 = load_from_excel(fname2, sheet_name=1)

correction1 = load_from_excel(fname1, sheet_name=0)
correction2 = load_from_excel(fname2, sheet_name=0)

# Dati di misura
I dati di misura sono stati ricavati da due esperimenti realizzati rispettivamente nelle date:
- Agosto 1954 - Novembre 1955
- Settembre 1957 - Dicembre 1957
Entrambi gli esperimenti sono stati effettuati nella stessa zona (Round Hill Field Station, Massachusetts Institute of Technology) con un setup simile.
Dettagli:
## Round Hill 1
### Emissione del gas
- Fonte di SO2 situata ad un'altezza di 30 cm dal livello del terreno
### Misure di concentrazione
- Le misure sono state effettuate in 3 semicirconferenze di raggio 50, 100, 200 m, con centro nella fonte del gas, tramite sensori posti lungo la circonferenza ad una distanza di 1.5 gradi l'uno dall'altro. Ogni sensore misura la concentrazione media di SO2 nell'aria per un periodo di 10 minuti

## Round Hill 2
### Emissione del gas
- Fonte di SO2 situata ad un'altezza di 1.5 m dal livello del terreno
### Misure di concentrazione
- Le misure sono state effettuate ad un'altezza di 1.5 m in 3 semicirconferenze di raggio 50, 100, 200 m con centro nella fonte del gas. In questo caso i sensori 1-6 e 106-111 sono distanziati di 3 gradi, mentre gli altri di 1.5 gradi. Le misure di concentrazione media sono state effettuate per un periodo di 10, 3, 1.5 min (Tutti gli intervalli di misurazione iniziano nello stesso istante)

### Misure meteorologiche (Round Hill 1 e Round Hill 2)
Durante l'esperimento sono state effettuate le seguenti misurazioni, in un periodo di 20 minuti centrato nei 10 minuti di misura:
- Velocità del vento media
- Temperatura
Questi due parametri sono stati misurati a diverse altezze (1.5, 3, 6 e 12 m)
- Distribuzione della direzione del vento
Quest'ultima è stata misurata ad un'altezza di 2 m

## Correzioni
I due dataset presentano dei fattori di correzione da applicare alle misure di concentrazione. Questi fattori moltiplicativi tengono conto dell'evaporazione della fonte di SO2, avvenuta più velocemente del previsto a causa delle temperature, portando quindi a misure di concentrazione più elevate

In [2]:
data1.head(10)

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6
0,NaN,Summary Excel Worksheet for Round Hill I (Disp...,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,Runs for which tracer may have flowed beneath ...,NaN,NaN,NaN,NaN,NaN
3,50,6,7,9,10,13.0,NaN
4,100,NaN,NaN,9,10,13.0,NaN
5,200,NaN,NaN,9,10,NaN,NaN
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,"From my analysis of Fig. 1, Post #1 looks to b...",NaN,NaN,NaN,NaN,NaN
8,NaN,"If you change D11, you alter all Post Azimuths",NaN,NaN,NaN,NaN,NaN
9,NaN,NaN,NaN,25,NaN,NaN,NaN

In [3]:
data2.head(10)

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21
0,NaN,Summary Excel Worksheet for Round Hill II (Dis...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,"From my analysis of Fig. 30, Post #1 looks to ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,"If you change D6, you alter all Post Azimuths",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,15,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,Appendix B. Table I. Sulfur-dioxide concentrat...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,NaN,and 10-min frequency distributions of azimuth ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Horizontal Sampling Array at 1.5m,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,VERTICAL SAMPLING RESULTS,NaN,NaN,NaN

In [7]:
meteo1.head(10)

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,Missing values = -99,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,On-Site Meteorology,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,All values reported are for the 10-min gas-sam...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,U - horizontal wind speed,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,Se - standard deviation of the bivane elevatio...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,NaN,Sa - standard deviation of the bivane horizont...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,NaN,Numbers following indicate height of the meteo...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,NaN,NaN,Appendix A. Table III. Summary of meteorologic...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,NaN,NaN,At Source,2m,NaN,NaN,NaN,NaN,Tower Meteorology,NaN,NaN,NaN,NaN
14,NaN,NaN,--------------------------------------,NaN,NaN,-------------------------------------------...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,NaN,Run,U2,Se2,Sa2,U1.5,U3.0,U6.0,U12.0,T1.5,T3.0,T6.0,T12.0
16,NaN,Number,(m/s),(deg),(deg),(m/s),(m/s),(m/s),(m/s),(deg C),(deg C),(deg C),(deg C)
17,NaN,1,2.17,11.2,30.4,-99,-99,-99,-99,-99,-99,-99,-99
18,NaN,2,4.04,6.1,17.6,-99,-99,-99,-99,-99,-99,-99,-99
19,NaN,3,2.84,5.3,12.5,-99,-99,-99,-99,-99,-99,-99,-99
20,NaN,4,2.62,10.8,31.5,-99,-99,-99,-99,-99,-99,-99,-99
21,NaN,5,5.25,4.6,13.9,-99,-99,-99,-99,-99,-99,-99,-99
22,NaN,6,4.21,4.9,15.5,3.73,4.34,4.7,5,4,3.73,3.59,3.38
23,NaN,7,8.76,4,8.4,7.94,9.21,10.3,-99,6,5.69,5.43,5.18
24,NaN,8,3.86,5.7,19.8,3.53,4.04,4.39,4.59,2.2,1.91,1.58,1.44
25,NaN,9,7.46,-99,11,6.77,7.79,8.65,9.46,0.4,0.1,-0.15,-0.41
26,NaN,10,7.12,-99,16.6,6.77,7.84,8.65,9.56,5.1,4.91,4.78,4.61
27,NaN,11,7.76,-99,13,7.08,8.24,8.95,9.71,6,6.01,6.02,5.99
28,NaN,12,4.3,5.1,18.6,3.99,4.49,4.85,5.2,5.9,5.48,5.17,4.8
29,NaN,13,9.2,-99,15.3,9.31,10.73,11.69,12.63,4,3.92,3.89,3.81
30,NaN,14,4.38,5.1,22,4.39,4.9,5.25,5.61,3.8,3.32,3.04,2.7
31,NaN,15,4.46,5.2,25.9,4.44,4.9,5.35,5.71,12.75,12.3,12.01,11.76
32,NaN,16,4.56,7.4,12.8,4.7,5.35,5.91,6.47,6.8,7.07,7.23,7.36
33,NaN,17,2.4,6.7,9.5,2.26,2.92,3.23,3.48,6.8,7.3,7.61,7.85
34,NaN,18,2.94,5.5,10.8,2.62,-99,3.63,4.09,15,15.17,15.26,15.31
35,NaN,19,2.71,5.9,11.8,2.47,-99,3.43,3.78,17,17.14,17.22,17.29
36,NaN,20,1.87,4,8.5,1.76,2.11,2.52,2.97,17,17.23,17.4,17.54
37,NaN,21,1.49,4.2,7.7,1.48,1.76,2.21,2.65,13.2,13.31,13.39,13.45
38,NaN,22,1.79,2.8,5.9,1.64,2.13,2.65,3.13,9.7,10.09,10.33,10.55
39,NaN,23,1.74,3.1,7.5,1.84,1.94,2.42,2.7,3.9,4.18,4.41,4.6
40,NaN,24,1.98,1.8,5.1,1.93,2.1,2.69,3.43,5.7,6.57,6.91,7.32
41,NaN,25,1.63,1.7,6.8,1.55,1.89,2.47,2.91,4.5,6.39,7.03,7.43
42,NaN,26,2.79,5.5,10.6,2.7,2.94,3.33,3.75,11,11.17,11.26,11.32
43,NaN,27,3.32,5.8,13.8,3.51,3.85,4.26,4.52,11.5,11.59,11.6,11.59
44,NaN,28,1.79,2.9,8.9,1.85,2.05,2.55,2.76,5.1,5.53,5.76,5.9
45,NaN,29,1.78,3.2,6.8,1.72,2.06,2.62,3.11,2.6,3.02,3.29,3.44

In [8]:
meteo2.head(10)

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,Missing values = -99,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,On-Site Meteorology,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,All values reported are for the 10-min gas-sam...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,U - horizontal wind speed,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,Se - standard deviation of the bivane elevatio...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,NaN,Sa - standard deviation of the bivane horizont...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,NaN,Numbers following indicate height of the meteo...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,NaN,NaN,Appendix B. Table IV. Summary of meteorologica...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,NaN,NaN,Cup Anemom.,NaN,NaN,NaN,Tower Observations,NaN,NaN,NaN,NaN,NaN
15,NaN,NaN,At Source (2 m),NaN,Horizontal Wind Speed (m/s),NaN,NaN,NaN,NaN,Temperature (C),NaN,NaN
16,NaN,RHill2,-------------------------,NaN,--------------------------------------------...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,NaN,Run,U(m/s),Sa(deg),U1.5,U3.0,U6.0,U12.0,T1.5,T3.0,T6.0,T12.0
18,NaN,1,2.14,8.4,2.52,2.87,3.28,3.78,12.12,12.51,12.73,12.94
19,NaN,2,5.15,16.5,5.36,6.12,6.57,6.98,20,19.54,19.33,18.97
20,NaN,3,3,12.9,3.19,3.57,3.97,4.34,14.92,15.12,15.24,15.3
21,NaN,4,3.98,16.7,3.99,4.44,4.85,5.05,13.4,13.27,13.19,13.09
22,NaN,5,1.65,9.2,-99,2.11,2.46,2.82,4.45,4.86,5.09,5.25
23,NaN,6,2.61,11.8,2.88,1.27,3.61,3.97,11.6,11.87,12.04,12.13
24,NaN,7,3.86,13.5,4.04,4.7,5.2,5.78,7.6,7.79,7.92,8.04
25,NaN,8,3.31,12.8,3.53,4.04,4.49,5,4.3,4.46,4.56,4.62
26,NaN,9,4.39,13.1,4.29,4.8,5.2,5.46,2.95,2.49,2.27,1.98
27,NaN,10,4.07,20.7,4.04,4.7,5.1,5.46,3.75,3.37,3.16,2.93

In [9]:
correction1.head(10)

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5
0,NaN,Appendix A. Table II. Concentrations listed in...,NaN,NaN,NaN,NaN
1,NaN,"be multiplied by values listed here, to compen...",NaN,NaN,NaN,NaN
2,NaN,evaporational loss of impinger solution during...,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,Run,Q,Evaporation Corrections,NaN,NaN
6,NaN,Number,(g/s),50,100.00,200.00
7,NaN,1,1,0.93,0.93,0.92
8,NaN,2,4.43,0.91,0.94,0.93
9,NaN,3,11.49,0.9,0.91,0.92
10,NaN,4,6.67,0.91,0.87,0.86
11,NaN,5,8.82,0.95,0.94,0.96
12,NaN,6,7.24,0.96,0.91,0.92
13,NaN,7,9.16,0.95,0.94,0.96
14,NaN,8,9.31,0.96,0.94,0.93
15,NaN,9,9.84,0.98,0.99,0.97
16,NaN,10,10.04,0.96,0.97,0.97
17,NaN,11,9.96,0.98,0.97,0.98
18,NaN,12,9.92,0.97,0.97,0.97
19,NaN,13,9.98,0.99,0.96,0.97
20,NaN,14,9.96,0.97,0.97,0.97
21,NaN,15,9.95,0.97,0.97,0.97
22,NaN,16,9.96,0.95,0.95,0.95
23,NaN,17,9.88,0.96,0.96,0.96
24,NaN,18,8.12,0.98,0.98,0.98
25,NaN,19,8.58,0.97,0.97,0.96
26,NaN,20,8.48,0.98,0.98,0.97
27,NaN,21,6.23,0.95,0.94,0.94
28,NaN,22,6.42,0.97,0.97,0.96
29,NaN,23,6.6,0.98,0.98,0.99
30,NaN,24,5.72,0.96,0.96,0.97
31,NaN,25,5.77,0.96,0.97,0.97
32,NaN,26,6.87,0.98,0.98,0.98
33,NaN,27,6.65,0.98,0.96,0.97
34,NaN,28,7.94,0.96,0.95,0.95
35,NaN,29,7.96,0.96,0.96,0.97

In [10]:
correction2.head(10)

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,Appendix B. Table II. Summary of source streng...,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,RHill2,Source Strength (g/s),NaN,NaN,Corrections,NaN,NaN
5,NaN,Run,10-min,3-min,0.5-min,10-min,3-min,0.5-min
6,NaN,1,45.1,45.1,45.1,0.9,0.92,0.83
7,NaN,2,109,114,115,0.91,0.93,0.9
8,NaN,3,53.4,53.4,53.4,0.93,0.95,0.95
9,NaN,4,100,108,108,0.92,0.92,0.91
10,NaN,5,49.2,49.2,49.2,0.97,0.99,0.98
11,NaN,6,53.1,54.2,54.2,0.96,0.98,0.97
12,NaN,7,56.5,56.5,56.5,0.92,0.94,0.95
13,NaN,8,53.8,71.2,71.2,0.91,0.94,0.95
14,NaN,9,71.2,73.6,73.6,0.96,0.97,0.98
15,NaN,10,93.4,97.5,97.5,0.94,0.96,0.97
16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,NaN,Note #1. During the last 8 minutes of release ...,NaN,NaN,NaN,NaN,NaN,NaN
18,NaN,strength decreased from about 70 g/s to about ...,NaN,NaN,NaN,NaN,NaN,NaN
19,NaN,should only affect the 10-min results.,NaN,NaN,NaN,NaN,NaN,NaN
20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,NaN,"Note #2. For release period #1, for the 0.5-mi...",NaN,NaN,NaN,NaN,NaN,NaN
22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,NaN,Concentration values listed in Appendix B. Tab...,NaN,NaN,NaN,NaN,NaN,NaN
24,NaN,for evaporational loss of impinger solution du...,NaN,NaN,NaN,NaN,NaN,NaN

# Interpretazione dei dati


### data1 - data2
Entrambi i dataset organizzati in un formato descrittivo, non adatto a processi di data analysis, cleaning o imputation.

Entrambi i dataset sono divisi in tabelle che contengono:
- Header (giorno, mese, anno, iterazione (run), intervallo orario)
- relhgt (altezza della fonte di SO2 dal terreno)

Colonne:
- Post: identificativo del sensore (intero)
- Degrees: angolo di inclinazione del sensore rispetto al sensore #1 (gradi)
- Azimuth: angolo di inclinazione del sensore rispetto al Nord (gradi)
- Wind-Dir: rappresenta quanto spesso la velocità del vento misurata è osservata al sensore. Questa misura è rappresentata in percentuale. La somma delle percentuali è posta in fondo alla rispettiva colonna (Non eguaglia sempre il 100%)
- Concentrazioni: colonna che racchiude 3 misure di concentrazione in $mg/m^3$ per le tre distanze considerate: 50, 100, 200 m

### Round Hill 2
Il secondo dataset è strutturato nello stesso modo. Le misure di concentrazione sono, questa volta, 9 in totale, 3 per ogni intervallo di tempo (10 min, 3 min, 1.5 min).<br>*La colonna relativa alla misurazione di concentrazione a 1.5 min è indicata con con "0.5-min", questo è probabilmente un errore avvenuto durante la trascrizione del dataset cartaceo*.<br>
Sono inoltre presenti misurazioni verticali, rispetto ai sensori, della concentrazione, rispettivamente a 2.5, 1.0, 0.5 m di altezza.

### meteo1 - meteo2
I due fogli contengono dati meteorologici registrati durante le misurazioni di concentrazione del gas.
Le colonne rappresentano:
- U (m/s) : velocità del vento orizzontale alla fonte
- Sa (deg) : deviazione standard dell'angolo di elevazione del vento misurato
- Se (deg) - Non presente in meteo2 : deviazione standard dell'angolo orizzontale del vento misurato
- U1.5, U3.0, U6.0, U12.0 (m/s) : velocità orizzontale del vento misurata ad altezze diverse (1.5 m, 3.0 m, 6.0 m, 12.0 m) da torri di osservazione situate nelle vicinanze della fonte del gas
- T1.5, T3.0, T6.0, T12.0 (C) : temperatura misurata dalle torri alle stesse altezze

Valori non rilevati vengono rappresentati da -99

### correction1 - correction2
I due fogli contengono i fattori di correzione moltiplicativi che tengono conto del tasso di evaporazione del gas. I valori sono compresi tra 0 e 1.0, riducendo la concentrazione effettiva del gas.
La colonna Q rappresenta il tasso di evaporazione del gas in g/s